s="Vaibhav Mulchandani"

print(len(s))
print(s)
print(s.capitalize())
print(s.casefold())
print(s.lower())
print(s.upper())
print(s.swapcase())
print(s.center(184,"*"))
print(s.count("o"))
print(s.endswith("ani"))
print(s.startswith("Va"))
print(s.find("chan"))
print(s.index("V"))
print("tops123".isalnum())
print("tops".isalnum())
print("123".isalnum())
print("tops 123".isalnum())
print("tops".isalpha())
print("123.10".isnumeric())
print("123.10".isdigit())
print("tops tech".istitle())
print("TOPS".isupper())
print("tops".islower())
print(" ".isspace())
